# This is a basic workflow to help you get started with Actions

name: Publish API Specification to Exchange

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  ORGANIZATION_ID: f60b1434-1059-4f0f-a28c-ccf4a9be05b2
  OWNER_ID: 612cf2dd-9f92-4a08-97ed-f6be4faf06ca
  CLASSIFIER: raml
  
  TOKEN: b6eaaaa1-4a10-4b05-b698-ec444674596d

jobs:
  import_to_design_center:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch all projects
        run: 'curl -s https://eu1.anypoint.mulesoft.com/designcenter/api-designer/projects --compressed -H "Authorization: Bearer $TOKEN" -H "x-organization-id: $ORGANIZATION_ID" "x-owner-id: $OWNER_ID" -H "Accept: application/json" -H "x-origin: GitHub Piepline" -H "Content-Type: application/json" -H "Accept-Encoding: gzip, deflate, br" -o projects.json'

      - name: Check if the project is already created
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Create the project
        run: echo Hello, world!

      - name: Acquire a lock
        run: echo Hello, world!

      - name: Add the main specification file
        run: echo Hello, world!

      - name: Release the lock
        run: echo Hello, world!

  publish_to_exchange:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Check if the project is already created
        run: echo Hello, world!
        
      - name: Publish the Exchange
        run: echo Hello, world!
