# This is a basic workflow to help you get started with Actions

name: Publish API Specification to Exchange

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  import_to_design_center:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch all projects
        run: echo Hello, world!

      - name: Check if the project is already created
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Create the project
        run: echo Hello, world!

      - name: Acquire a lock
        run: echo Hello, world!

      - name: Add the main specification file
        run: echo Hello, world!

      - name: Release the lock
        run: echo Hello, world!

  publish_to_exchange:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Check if the project is already created
        run: echo Hello, world!
        
      - name: Publish the Exchange
        run: echo Hello, world!
